title = "YouTube-downloader-tkinter, Lari Liuhamo @2017"
url_box = "Video URLs"
dl_button = "Start download"
quit_button = "Exit"
dl_complete = "Done downloading, now converting ..."
convert_complete = "File format converted successfully"

tb_file = "File"
tb_file_cfg = "Settings"

tb_help = "Help"
tb_help_about = "About"
tb_help_usage = "Usage"
tb_help_license = "License"

cfg_title = "YDL Settings"

cfg_out = "Output (video/audio):"
cfg_out_vd = "Video"
cfg_out_aud = "Audio-only"

cfg_lang = "GUI language:"
